# Generated by Django 2.1.7 on 2019-03-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bethink', '0002_auto_20190325_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='notification_date',
            field=models.DateTimeField(null=True),
        ),
    ]
