# Generated by Django 2.1.7 on 2019-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bethink', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(max_length=20)),
                ('notification_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
