# Generated by Django 2.1.7 on 2019-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bethink', '0006_auto_20190327_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
