# Generated by Django 2.1.7 on 2019-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bethink', '0007_auto_20190327_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
