# Generated by Django 2.1.7 on 2019-03-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bethink', '0009_auto_20190328_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
