# Generated by Django 2.1.7 on 2019-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bethink', '0010_tgmessage_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
